server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/regd_users?createDatabaseIfNotExist=true
    username: root
    password: Jayanth@23
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


# create, validate, update